# Generated by Django 5.2 on 2025-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
