# Generated by Django 5.2 on 2025-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0009_add_to_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
