# Generated by Django 5.2 on 2025-05-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0010_add_to_wishlist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=50, null=True)),
                ('Last_name', models.TextField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.TextField(blank=True, max_length=200, null=True)),
                ('postcode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruitables.user')),
            ],
        ),
    ]
