# Generated by Django 5.2 on 2025-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0011_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='Last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
