# Generated by Django 5.2 on 2025-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0012_billing_details_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
