# Generated by Django 5.2 on 2025-05-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0013_alter_billing_details_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_details',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
