# Generated by Django 5.2 on 2025-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitables', '0014_rename_last_name_billing_details_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
